#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/CheckboxList.cshtml")]
    public partial class _Views_Shared_EditorTemplates_CheckboxList_cshtml_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_EditorTemplates_CheckboxList_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
  

    var list = ViewData["List"] as List<SelectListItem>;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"checkbox-group\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
     foreach (var item in list)
    {

            
            #line default
            #line hidden
WriteLiteral("        <label");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: data.");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
                                                        Write(ViewData.ModelMetadata.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("value", Tuple.Create(" value=\"", 279), Tuple.Create("\"", 300)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
                             , Tuple.Create(Tuple.Create("", 287), Tuple.Create<System.Object, System.Int32>(item.Value
            
            #line default
            #line hidden
, 287), false)
);

WriteLiteral("> ");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
                                                                                                                      Write(item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </label>\r\n");

            
            #line 12 "..\..\Views\Shared\EditorTemplates\CheckboxList.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
