#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Object.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Object_cshtml_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_EditorTemplates_Object_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
 if (ViewData.TemplateInfo.TemplateDepth > 1)
{
    if (Model == null)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("ViewData.ModelMetadata.NullDisplayText");

WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("ViewData.ModelMetadata.SimpleDisplayText");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
    }
}
else
{
    foreach (var prop in ViewData.ModelMetadata.Properties.Where(metadata => metadata.ShowForEdit
        // && metadata.ModelType != typeof(System.Data.EntityState) // Dependency on Entity Framework present in Microsoft.Web.Mvc template
                                                                             && !metadata.IsComplexType
                                                                             && !ViewData.TemplateInfo.Visited(metadata)))
    {
        if (prop.HideSurroundingHtml)
        {
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
       Write(Html.Editor(prop.PropertyName));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
                                           
        }
        else
        {
            var label = Html.Label(prop.PropertyName).ToHtmlString();
            if (!string.IsNullOrEmpty(label))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
                                     Write(Html.Label(prop.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 29 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
                                 Write(Html.Editor(prop.PropertyName));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 30 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
                                                                 Write(Html.ValidationMessage(prop.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 31 "..\..\Views\Shared\EditorTemplates\Object.cshtml"
        }
    }
}
            
            #line default
            #line hidden
WriteLiteral(" ");

        }
    }
}
#pragma warning restore 1591
