#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class Btn : System.Web.WebPages.HelperPage
    {

#line 3 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForAttention(string id, bool isFollow, string role = null)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 4 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
if (true)
{
    var btnText = isFollow ? "取消关注" : "关注";
    var iconCls = isFollow ? "fa-eye-slash" : "fa-eye";



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <a");

WriteLiteralTo(__razor_helper_writer, " class=\"btn btn-default\"");

WriteLiteralTo(__razor_helper_writer, " data-action=\"attention\"");

WriteLiteralTo(__razor_helper_writer, " data-id=\"");


#line 10 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                       WriteTo(__razor_helper_writer, id);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-isfollow=\"");


#line 10 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                             WriteTo(__razor_helper_writer, isFollow);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 388), Tuple.Create("\"", 409)
, Tuple.Create(Tuple.Create("", 396), Tuple.Create("fa", 396), true)

#line 11 "..\..\Views\Shared\Helpers\Btn.cshtml"
, Tuple.Create(Tuple.Create(" ", 398), Tuple.Create<System.Object, System.Int32>(iconCls

#line default
#line hidden
, 399), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");

WriteLiteralTo(__razor_helper_writer, "            ");


#line 12 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, btnText);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n        </a>\r\n");


#line 14 "..\..\Views\Shared\Helpers\Btn.cshtml"
}


#line default
#line hidden
});

#line 15 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 17 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForNext(string btnClass = "btn-default", string action = "next", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 18 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 19 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "arrow-right", "下一步", role, hasText: hasText));


#line default
#line hidden

#line 19 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                                   


#line default
#line hidden
});

#line 20 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 22 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForSave()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 23 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 24 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton("btn-primary", "save", "save", "保存"));


#line default
#line hidden

#line 24 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                        


#line default
#line hidden
});

#line 25 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 27 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForAdd(string btnClass = "btn-default", string action = "create", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 28 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 29 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "plus", "添加", role, hasText: hasText));


#line default
#line hidden

#line 29 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                           


#line default
#line hidden
});

#line 30 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 32 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForDelete(string btnClass = "btn-default", string action = "remove", string icon = null, string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 33 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 34 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, icon, "删除", role, hasText: hasText));


#line default
#line hidden

#line 34 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                         


#line default
#line hidden
});

#line 35 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 37 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForDetail(string btnClass = "btn-default", string action = "detail", string text = "", string icon = null, string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 38 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 39 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, icon, "详情", role, hasText: hasText));


#line default
#line hidden

#line 39 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                         


#line default
#line hidden
});

#line 40 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 42 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForRefresh(string btnClass = "btn-default", string action = "refresh", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 43 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 44 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "refresh", "刷新", role, hasText: hasText));


#line default
#line hidden

#line 44 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                              


#line default
#line hidden
});

#line 45 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 47 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForSearch(string btnClass = "btn-default", string action = "search", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 48 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 49 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "search", "查询", role, hasText: hasText));


#line default
#line hidden

#line 49 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                             


#line default
#line hidden
});

#line 50 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 52 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForDownload(string btnClass = "btn-default", string action = "download", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 53 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 54 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "download", "下载", role, hasText: hasText));


#line default
#line hidden

#line 54 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                               


#line default
#line hidden
});

#line 55 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 57 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForEdit(string btnClass = "btn-success", string action = "edit", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 58 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 59 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "edit", "编辑", role, hasText: hasText));


#line default
#line hidden

#line 59 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                           


#line default
#line hidden
});

#line 60 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 62 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForModify(string btnClass = "btn-default", string action = "modify", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 63 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 64 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "edit", "编辑", role, hasText: hasText));


#line default
#line hidden

#line 64 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                           


#line default
#line hidden
});

#line 65 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 67 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForClose(string btnClass = "btn-default", string action = "close", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 68 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 69 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "close", "关闭", role, hasText: hasText));


#line default
#line hidden

#line 69 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                            


#line default
#line hidden
});

#line 70 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 72 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult ButtonForBack(string btnClass = "btn-default", string action = "back", string role = null, bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 73 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
    

#line default
#line hidden

#line 74 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, SecurityButton(btnClass, action, "arrow-left", "返回", role, hasText: hasText));


#line default
#line hidden

#line 74 "..\..\Views\Shared\Helpers\Btn.cshtml"
                                                                                 


#line default
#line hidden
});

#line 75 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

#line 77 "..\..\Views\Shared\Helpers\Btn.cshtml"
public static System.Web.WebPages.HelperResult SecurityButton(string btnClass = "btn-default", string action = "", string icon = null, string text = "", string role = null, string title = "", bool hasText = true)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 78 "..\..\Views\Shared\Helpers\Btn.cshtml"
 
if (true)
{
    var className = "btn " + btnClass;
    var iconClass = "";
    var theTitle = hasText == false && string.IsNullOrEmpty(title) ? text : title;
    if (!string.IsNullOrEmpty(icon))
    {
        iconClass = "fa fa-" + icon;
    }



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <a");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 3370), Tuple.Create("\"", 3388)

#line 89 "..\..\Views\Shared\Helpers\Btn.cshtml"
, Tuple.Create(Tuple.Create("", 3378), Tuple.Create<System.Object, System.Int32>(className

#line default
#line hidden
, 3378), false)
);

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 3389), Tuple.Create("\"", 3406)

#line 89 "..\..\Views\Shared\Helpers\Btn.cshtml"
, Tuple.Create(Tuple.Create("", 3397), Tuple.Create<System.Object, System.Int32>(theTitle

#line default
#line hidden
, 3397), false)
);

WriteLiteralTo(__razor_helper_writer, " data-action=\"");


#line 89 "..\..\Views\Shared\Helpers\Btn.cshtml"
                           WriteTo(__razor_helper_writer, action);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 90 "..\..\Views\Shared\Helpers\Btn.cshtml"
        

#line default
#line hidden

#line 90 "..\..\Views\Shared\Helpers\Btn.cshtml"
         if (!string.IsNullOrEmpty(iconClass))
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 3505), Tuple.Create("\"", 3523)

#line 92 "..\..\Views\Shared\Helpers\Btn.cshtml"
, Tuple.Create(Tuple.Create("", 3513), Tuple.Create<System.Object, System.Int32>(iconClass

#line default
#line hidden
, 3513), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


#line 93 "..\..\Views\Shared\Helpers\Btn.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");


#line 94 "..\..\Views\Shared\Helpers\Btn.cshtml"
         if (hasText)
        {
            

#line default
#line hidden

#line 96 "..\..\Views\Shared\Helpers\Btn.cshtml"
WriteTo(__razor_helper_writer, text);


#line default
#line hidden

#line 96 "..\..\Views\Shared\Helpers\Btn.cshtml"
                 
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </a>\r\n");


#line 99 "..\..\Views\Shared\Helpers\Btn.cshtml"
}


#line default
#line hidden
});

#line 100 "..\..\Views\Shared\Helpers\Btn.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
