#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class Form : System.Web.WebPages.HelperPage
    {
        
        #line 3 "..\..\Views\Shared\Helpers\Form.cshtml"
 

    public static string GetDataFormat(ModelMetadata metadata)
    {
        var dataFormat = string.Empty;


        if (!string.IsNullOrEmpty(metadata.DisplayFormatString))
        {
            dataFormat = metadata.DisplayFormatString.Replace("{", "").Replace("}", "").Replace("0:", "");
        }
        else
        {
            if (metadata.DataTypeName == "Currency" || metadata.ModelType.Name == "Decimal")
            {
                dataFormat = "C";
            }
        }
        return dataFormat;
    }


        #line default
        #line hidden

#line 26 "..\..\Views\Shared\Helpers\Form.cshtml"
public static System.Web.WebPages.HelperResult SecurityCheckBox(string chkClass = "attention", bool isChecked = false, string text = "关注", string role = null)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 27 "..\..\Views\Shared\Helpers\Form.cshtml"
 
    // if (Helper.HasPermission(role))
    if(true)
    {
        if (isChecked)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <input");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteLiteralTo(__razor_helper_writer, " checked=\"checked\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 909), Tuple.Create("\"", 926)

#line 33 "..\..\Views\Shared\Helpers\Form.cshtml"
, Tuple.Create(Tuple.Create("", 917), Tuple.Create<System.Object, System.Int32>(chkClass

#line default
#line hidden
, 917), false)
);

WriteLiteralTo(__razor_helper_writer, "/>\r\n");


#line 34 "..\..\Views\Shared\Helpers\Form.cshtml"
            

#line default
#line hidden

#line 34 "..\..\Views\Shared\Helpers\Form.cshtml"
WriteTo(__razor_helper_writer, text);


#line default
#line hidden

#line 34 "..\..\Views\Shared\Helpers\Form.cshtml"
                 
        }
        else
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <input");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1020), Tuple.Create("\"", 1037)

#line 38 "..\..\Views\Shared\Helpers\Form.cshtml"
, Tuple.Create(Tuple.Create("", 1028), Tuple.Create<System.Object, System.Int32>(chkClass

#line default
#line hidden
, 1028), false)
);

WriteLiteralTo(__razor_helper_writer, "/>\r\n");


#line 39 "..\..\Views\Shared\Helpers\Form.cshtml"
            

#line default
#line hidden

#line 39 "..\..\Views\Shared\Helpers\Form.cshtml"
WriteTo(__razor_helper_writer, text);


#line default
#line hidden

#line 39 "..\..\Views\Shared\Helpers\Form.cshtml"
                 
        }
    }


#line default
#line hidden
});

#line 42 "..\..\Views\Shared\Helpers\Form.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
