#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class Nav : System.Web.WebPages.HelperPage
    {

#line 3 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult Breadcrumb(List<SelectListItemDto> list, string actionName = "refresh")
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 4 "..\..\Views\Shared\Helpers\Nav.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <ol");

WriteLiteralTo(__razor_helper_writer, " class=\"breadcrumb no-margin\"");

WriteLiteralTo(__razor_helper_writer, " style=\"border-bottom: 1px solid #ddd; min-height: 26px;\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 6 "..\..\Views\Shared\Helpers\Nav.cshtml"
        

#line default
#line hidden

#line 6 "..\..\Views\Shared\Helpers\Nav.cshtml"
         for (var i = 0; i < list.Count; i++)
        {
            var item = list[i];
            if (i == list.Count - 1)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <li");

WriteLiteralTo(__razor_helper_writer, " data-value=\"");


#line 11 "..\..\Views\Shared\Helpers\Nav.cshtml"
  WriteTo(__razor_helper_writer, item.Value);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-data=\"");


#line 11 "..\..\Views\Shared\Helpers\Nav.cshtml"
                          WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 11 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                      WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</li>\r\n");


#line 12 "..\..\Views\Shared\Helpers\Nav.cshtml"
            }
            else
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <li>\r\n                    <a");

WriteLiteralTo(__razor_helper_writer, " href=\"#\"");

WriteLiteralTo(__razor_helper_writer, " data-action=\"");


#line 16 "..\..\Views\Shared\Helpers\Nav.cshtml"
               WriteTo(__razor_helper_writer, actionName);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-value=\"");


#line 16 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                        WriteTo(__razor_helper_writer, item.Value);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, " data-data=\"");


#line 16 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                                                WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 16 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                                                            WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n                </li>\r\n");


#line 18 "..\..\Views\Shared\Helpers\Nav.cshtml"
            }
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </ol>\r\n");


#line 21 "..\..\Views\Shared\Helpers\Nav.cshtml"


#line default
#line hidden
});

#line 21 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

#line 23 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult MenuItem(MenuItem item)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 24 "..\..\Views\Shared\Helpers\Nav.cshtml"
 
    var hasChildren = item.Items.Count > 0;
    var aClass = hasChildren ? "dropdown-toggle" : string.Empty;
    // if (Helper.HasPermission(item.Role))
    if(true)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <li");

WriteLiteralTo(__razor_helper_writer, " class=\"menu-item\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 999), Tuple.Create("\"", 1015)

#line 31 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1006), Tuple.Create<System.Object, System.Int32>(item.Url

#line default
#line hidden
, 1006), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1016), Tuple.Create("\"", 1033)

#line 31 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1024), Tuple.Create<System.Object, System.Int32>(aClass

#line default
#line hidden
, 1024), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 32 "..\..\Views\Shared\Helpers\Nav.cshtml"
                

#line default
#line hidden

#line 32 "..\..\Views\Shared\Helpers\Nav.cshtml"
                 if (!string.IsNullOrEmpty(item.Icon))
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1134), Tuple.Create("\"", 1170)
, Tuple.Create(Tuple.Create("", 1142), Tuple.Create("menu-icon", 1142), true)
, Tuple.Create(Tuple.Create(" ", 1151), Tuple.Create("fa", 1152), true)
, Tuple.Create(Tuple.Create(" ", 1154), Tuple.Create("fa-", 1155), true)

#line 34 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create<System.Object, System.Int32>(item.Icon

#line default
#line hidden
, 1158), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


#line 35 "..\..\Views\Shared\Helpers\Nav.cshtml"
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"menu-text\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 36 "..\..\Views\Shared\Helpers\Nav.cshtml"
          WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>\r\n            </a>\r\n");


#line 38 "..\..\Views\Shared\Helpers\Nav.cshtml"
            

#line default
#line hidden

#line 38 "..\..\Views\Shared\Helpers\Nav.cshtml"
             if (item.Items.Count > 0)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <ul");

WriteLiteralTo(__razor_helper_writer, " class=\"submenu\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 41 "..\..\Views\Shared\Helpers\Nav.cshtml"
                    

#line default
#line hidden

#line 41 "..\..\Views\Shared\Helpers\Nav.cshtml"
                     foreach (var subItem in item.Items)
                    {
                        

#line default
#line hidden

#line 43 "..\..\Views\Shared\Helpers\Nav.cshtml"
WriteTo(__razor_helper_writer, MenuItem(subItem));


#line default
#line hidden

#line 43 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                          
                    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </ul>\r\n");


#line 46 "..\..\Views\Shared\Helpers\Nav.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </li>\r\n");


#line 48 "..\..\Views\Shared\Helpers\Nav.cshtml"
    }


#line default
#line hidden
});

#line 49 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

#line 50 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult Menu(List<MenuItem> menu)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 51 "..\..\Views\Shared\Helpers\Nav.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <ul");

WriteLiteralTo(__razor_helper_writer, " class=\"nav nav-list\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 53 "..\..\Views\Shared\Helpers\Nav.cshtml"
        

#line default
#line hidden

#line 53 "..\..\Views\Shared\Helpers\Nav.cshtml"
         foreach (var item in menu)
        {
            

#line default
#line hidden

#line 55 "..\..\Views\Shared\Helpers\Nav.cshtml"
WriteTo(__razor_helper_writer, MenuItem(item));


#line default
#line hidden

#line 55 "..\..\Views\Shared\Helpers\Nav.cshtml"
                           
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </ul>\r\n");


#line 58 "..\..\Views\Shared\Helpers\Nav.cshtml"


#line default
#line hidden
});

#line 58 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

#line 60 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult SiteMapMenuItem(ISiteMapNode node)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 61 "..\..\Views\Shared\Helpers\Nav.cshtml"
 
    var aClass = node.HasChildNodes ? "dropdown-toggle" : string.Empty;
    var role = string.Join(",", node.Roles);
    //if (Helper.HasPermission(role))
    if(true)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <li");

WriteLiteralTo(__razor_helper_writer, " class=\"menu-item\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n            <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 2023), Tuple.Create("\"", 2039)

#line 68 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 2030), Tuple.Create<System.Object, System.Int32>(node.Url

#line default
#line hidden
, 2030), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 2040), Tuple.Create("\"", 2057)

#line 68 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 2048), Tuple.Create<System.Object, System.Int32>(aClass

#line default
#line hidden
, 2048), false)
);

WriteAttributeTo(__razor_helper_writer, "title", Tuple.Create(" title=\"", 2058), Tuple.Create("\"", 2099)

#line 68 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 2066), Tuple.Create<System.Object, System.Int32>(node.Description ?? node.Title

#line default
#line hidden
, 2066), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 69 "..\..\Views\Shared\Helpers\Nav.cshtml"
                

#line default
#line hidden

#line 69 "..\..\Views\Shared\Helpers\Nav.cshtml"
                 if (!string.IsNullOrEmpty(node.ImageUrl))
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    <i");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 2204), Tuple.Create("\"", 2261)
, Tuple.Create(Tuple.Create("", 2212), Tuple.Create("menu-icon", 2212), true)
, Tuple.Create(Tuple.Create(" ", 2221), Tuple.Create("fa", 2222), true)
, Tuple.Create(Tuple.Create(" ", 2224), Tuple.Create("fa-", 2225), true)

#line 71 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 2228), Tuple.Create<System.Object, System.Int32>(node.ImageUrl.Replace("/", "")

#line default
#line hidden
, 2228), false)
);

WriteLiteralTo(__razor_helper_writer, "></i>\r\n");


#line 72 "..\..\Views\Shared\Helpers\Nav.cshtml"
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <span");

WriteLiteralTo(__razor_helper_writer, " class=\"menu-text\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 73 "..\..\Views\Shared\Helpers\Nav.cshtml"
          WriteTo(__razor_helper_writer, node.Title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>\r\n            </a>\r\n");


#line 75 "..\..\Views\Shared\Helpers\Nav.cshtml"
            

#line default
#line hidden

#line 75 "..\..\Views\Shared\Helpers\Nav.cshtml"
             if (node.HasChildNodes)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <ul");

WriteLiteralTo(__razor_helper_writer, " class=\"submenu\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 78 "..\..\Views\Shared\Helpers\Nav.cshtml"
                    

#line default
#line hidden

#line 78 "..\..\Views\Shared\Helpers\Nav.cshtml"
                     foreach (var childNode in node.ChildNodes)
                    {
                        

#line default
#line hidden

#line 80 "..\..\Views\Shared\Helpers\Nav.cshtml"
WriteTo(__razor_helper_writer, SiteMapMenuItem(childNode));


#line default
#line hidden

#line 80 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                                   
                    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </ul>\r\n");


#line 83 "..\..\Views\Shared\Helpers\Nav.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </li>\r\n");


#line 85 "..\..\Views\Shared\Helpers\Nav.cshtml"
    }


#line default
#line hidden
});

#line 86 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

#line 87 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult SiteMapMenu(ISiteMap sitemap)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 88 "..\..\Views\Shared\Helpers\Nav.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <ul");

WriteLiteralTo(__razor_helper_writer, " class=\"nav nav-list\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 90 "..\..\Views\Shared\Helpers\Nav.cshtml"
        

#line default
#line hidden

#line 90 "..\..\Views\Shared\Helpers\Nav.cshtml"
         foreach (var node in sitemap.GetChildNodes(sitemap.RootNode))
        {
            

#line default
#line hidden

#line 92 "..\..\Views\Shared\Helpers\Nav.cshtml"
WriteTo(__razor_helper_writer, SiteMapMenuItem(node));


#line default
#line hidden

#line 92 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                  
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </ul>\r\n");


#line 95 "..\..\Views\Shared\Helpers\Nav.cshtml"


#line default
#line hidden
});

#line 95 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

#line 97 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult Tabs(List<MenuItem> items, int activeIndex = 0, List<int> noneIndexs = null)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 98 "..\..\Views\Shared\Helpers\Nav.cshtml"
 
    var rendered = false;
    noneIndexs = noneIndexs ?? new List<int>();


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"tabbable\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n        <ul");

WriteLiteralTo(__razor_helper_writer, " class=\"nav nav-tabs padding-14\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 103 "..\..\Views\Shared\Helpers\Nav.cshtml"
            

#line default
#line hidden

#line 103 "..\..\Views\Shared\Helpers\Nav.cshtml"
             for (var i = 0; i < items.Count; i++)
            {
                var item = items[i];
                var itemCls = activeIndex == i ? "active" : "";
                //var canRender = !noneIndexs.Contains(i) && Helper.HasPermission(item.Role);
                var canRender = !noneIndexs.Contains(i) && true;
                if (canRender && !rendered && activeIndex == 0)
                {
                    itemCls = "active";
                }
                if (canRender)
                {
                    rendered = true;
                }
                if (canRender)
                {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                    <li");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 3799), Tuple.Create("\"", 3817)

#line 119 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 3807), Tuple.Create<System.Object, System.Int32>(itemCls

#line default
#line hidden
, 3807), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n                        <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 3847), Tuple.Create("\"", 3865)

#line 120 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 3854), Tuple.Create<System.Object, System.Int32>(item.Url

#line default
#line hidden
, 3854), false)
);

WriteLiteralTo(__razor_helper_writer, " data-toggle=\"tab\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 120 "..\..\Views\Shared\Helpers\Nav.cshtml"
                                  WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n                    </li>\r\n");


#line 122 "..\..\Views\Shared\Helpers\Nav.cshtml"
                }
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </ul>\r\n    </div>\r\n");


#line 126 "..\..\Views\Shared\Helpers\Nav.cshtml"


#line default
#line hidden
});

#line 126 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

#line 128 "..\..\Views\Shared\Helpers\Nav.cshtml"
public static System.Web.WebPages.HelperResult TabPanels(List<MenuItem> items, int activeIndex = 0, List<int> noneIndexs = null)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 129 "..\..\Views\Shared\Helpers\Nav.cshtml"
 
    var rendered = false;
    noneIndexs = noneIndexs ?? new List<int>();


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"tab-content full-h\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 133 "..\..\Views\Shared\Helpers\Nav.cshtml"
        

#line default
#line hidden

#line 133 "..\..\Views\Shared\Helpers\Nav.cshtml"
         for (var i = 0; i < items.Count; i++)
        {
            var item = items[i];
            var itemCls = activeIndex == i ? "active" : "";
            //var canRender = !noneIndexs.Contains(i) && Helper.HasPermission(item.Role);
            var canRender = !noneIndexs.Contains(i) && true;
            if (canRender && !rendered && activeIndex == 0)
            {
                itemCls = "active";
            }
            if (canRender)
            {
                rendered = true;
            }
            if (canRender)
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <div");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 4792), Tuple.Create("\"", 4821)

#line 149 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 4797), Tuple.Create<System.Object, System.Int32>(item.Url.Substring(1)

#line default
#line hidden
, 4797), false)
);

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 4822), Tuple.Create("\"", 4877)

#line 149 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create("", 4830), Tuple.Create<System.Object, System.Int32>(item.ClassName

#line default
#line hidden
, 4830), false)

#line 149 "..\..\Views\Shared\Helpers\Nav.cshtml"
, Tuple.Create(Tuple.Create(" ", 4847), Tuple.Create<System.Object, System.Int32>(itemCls

#line default
#line hidden
, 4848), false)
, Tuple.Create(Tuple.Create(" ", 4858), Tuple.Create("tab-pane", 4859), true)
, Tuple.Create(Tuple.Create(" ", 4867), Tuple.Create("in", 4868), true)
, Tuple.Create(Tuple.Create(" ", 4870), Tuple.Create("full-v", 4871), true)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n                </div>\r\n");


#line 151 "..\..\Views\Shared\Helpers\Nav.cshtml"
            }
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </div>\r\n");


#line 154 "..\..\Views\Shared\Helpers\Nav.cshtml"


#line default
#line hidden
});

#line 154 "..\..\Views\Shared\Helpers\Nav.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
