#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partials/_LayoutScript.cshtml")]
    public partial class _Views_Shared_Partials__LayoutScript_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Partials__LayoutScript_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var siteRoot = \'");

            
            #line 2 "..\..\Views\Shared\Partials\_LayoutScript.cshtml"
               Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n</script>\r\n");

            
            #line 4 "..\..\Views\Shared\Partials\_LayoutScript.cshtml"
 if (Html.IsDebug())
{

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" data-main=\"app/main\"");

WriteAttribute("src", Tuple.Create(" src=\"", 143), Tuple.Create("\"", 172)
, Tuple.Create(Tuple.Create("", 149), Tuple.Create<System.Object, System.Int32>(Href("~/app/assets/require.js")
, 149), false)
);

WriteLiteral("></script>\r\n");

            
            #line 7 "..\..\Views\Shared\Partials\_LayoutScript.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" data-main=\"release/main\"");

WriteAttribute("src", Tuple.Create(" src=\"", 233), Tuple.Create("\"", 266)
, Tuple.Create(Tuple.Create("", 239), Tuple.Create<System.Object, System.Int32>(Href("~/release/assets/require.js")
, 239), false)
);

WriteLiteral("></script>\r\n");

            
            #line 11 "..\..\Views\Shared\Partials\_LayoutScript.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
