using System;
using System.ComponentModel.DataAnnotations;
using Orzoo.Core.Enums;

namespace Orzoo.Core.Data
{
    public class BasicEntity : Entity, INamedEntity, IAutoGenerateDateEntity, IFlagEntity, IAccessSecurityEntity
    {

        [Display(Name = "名称")]
        public virtual string Name { get; set; }

        #region AutoGenerateDate

        public virtual DateTime? CreatedDate { get; set; }
        public virtual DateTime? LastModifiedDate { get; set; }
        public virtual string CreatedUser { get; set; }
        public virtual string ModifiedUser { get; set; }

        #endregion

        public DataFlag? Flag { get; set; } = DataFlag.Valid;
        public string Accesses { get; set; }
        public string GetAccessSecurityRoot()
        {
            return string.Empty;
        }

        public bool EnableAccessSecurity()
        {
            return true;
        }

    }
}
