using System;
using System.ComponentModel.DataAnnotations;
using Orzoo.Core.Enums;

namespace Orzoo.Core.Data
{
    /// <summary>
    /// 基础实体
    /// </summary>
    public class BasicEntity : Entity, INamedEntity, IMetadataEntity, IFlagEntity
    {

        [Display(Name = "名称")]
        public virtual string Name { get; set; }

        #region AutoGenerateDate

        public virtual DateTime? CreatedDate { get; set; }
        public virtual DateTime? LastModifiedDate { get; set; }
        public virtual string CreatedUser { get; set; }
        public virtual string ModifiedUser { get; set; }

        #endregion

        public DataFlag? Flag { get; set; } = DataFlag.Valid;

    }
}
