#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/_MainPanelLayout.cshtml")]
    public partial class _Views_Shared_Layouts__MainPanelLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts__MainPanelLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"panel panel-transparent panel-underline no-border flexbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading clearfix\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"panel-title pull-left\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 4 "..\..\Views\Shared\Layouts\_MainPanelLayout.cshtml"
       Write(RenderSection("Title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </h3>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-toolbar panel-toolbar-sm\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Shared\Layouts\_MainPanelLayout.cshtml"
   Write(RenderSection("Toolbar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body no-padding grow inline\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Shared\Layouts\_MainPanelLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-footer no-padding\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Shared\Layouts\_MainPanelLayout.cshtml"
   Write(RenderSection("Footer", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

            
            #line 17 "..\..\Views\Shared\Layouts\_MainPanelLayout.cshtml"
Write(RenderSection("Tpl", false));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
