#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/DisplaySection.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_DisplaySection_cshtml_ : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 10 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
public System.Web.WebPages.HelperResult RenderDisplay(TemplateParams templateParams)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 11 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
 
    var labelClass = templateParams.GetAdditionalViewData("LabelClass");
    var controlClass = templateParams.GetAdditionalViewData("ControlClass");
    var controlTemplate = templateParams.GetAdditionalViewData("UIHint")?.ToString() ?? ViewData.ModelMetadata.TemplateHint;
    // 处理日期的赋值
    var typeName = ValueHelper.GetJsType(ViewData.ModelMetadata.ModelType);
    var valueField = typeName == "date" ? "date" : "text";

    var addtionCls = controlTemplate == "Hidden" ? "hidden" : string.Empty;


    if (controlTemplate != "Hidden")
    {
        

#line default
#line hidden

#line 24 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
WriteTo(__razor_helper_writer, Html.LabelFor(m => m, new {@class = labelClass, title = Html.DisplayNameFor(m => m)}));


#line default
#line hidden

#line 24 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
                                                                                              
    }

    if (templateParams.Features.Contains(TemplateFeature.DataBind))
    {
        var dataBind = controlTemplate == "Link" ? ""
            : valueField + ": data." + ViewData.ModelMetadata.PropertyName + ", attr:{ title: data." + ViewData.ModelMetadata.PropertyName + "}";


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <span");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1380), Tuple.Create("\"", 1417)

#line 31 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
, Tuple.Create(Tuple.Create("", 1388), Tuple.Create<System.Object, System.Int32>(controlClass

#line default
#line hidden
, 1388), false)

#line 31 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
, Tuple.Create(Tuple.Create(" ", 1403), Tuple.Create<System.Object, System.Int32>(addtionCls

#line default
#line hidden
, 1404), false)
);

WriteLiteralTo(__razor_helper_writer, "\r\n                  data-type=\"");


#line 32 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
WriteTo(__razor_helper_writer, typeName);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, "\r\n                  data-format=\"");


#line 33 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
  WriteTo(__razor_helper_writer, Form.GetDataFormat(ViewData.ModelMetadata));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, "\r\n                  data-bind=\"");


#line 34 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
WriteTo(__razor_helper_writer, dataBind);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 35 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
WriteTo(__razor_helper_writer, Html.DisplayFor(m => m, controlTemplate, templateParams.HtmlFieldName, templateParams.AdditionalViewData));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </span>\r\n");


#line 37 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
    }
    else
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <span");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1768), Tuple.Create("\"", 1805)

#line 40 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
, Tuple.Create(Tuple.Create("", 1776), Tuple.Create<System.Object, System.Int32>(controlClass

#line default
#line hidden
, 1776), false)

#line 40 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
, Tuple.Create(Tuple.Create(" ", 1791), Tuple.Create<System.Object, System.Int32>(addtionCls

#line default
#line hidden
, 1792), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 41 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
WriteTo(__razor_helper_writer, Html.DisplayFor(m => m, controlTemplate, templateParams.HtmlFieldName, templateParams.AdditionalViewData));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n            </span>\r\n");


#line 43 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
    }


#line default
#line hidden
});

#line 44 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
}
#line default
#line hidden

        public _Views_Shared_DisplayTemplates_DisplaySection_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
  

    TemplateHelper.RemoveModelFromVisitedObjects(ViewData);

    var templateParams = ViewData["TemplateParams"] as TemplateParams ?? new TemplateParams();

    //var dataBind = templateParams.GetAdditionalViewData("DataBind");
    var controlTemplate = templateParams.GetAdditionalViewData("UIHint")?.ToString() ?? ViewData.ModelMetadata.TemplateHint;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 45 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
 if (templateParams.Features.Contains(TemplateFeature.GridLayout) && controlTemplate != "Hidden")
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 48 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
   Write(RenderDisplay(templateParams));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 50 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
}
else
{
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
Write(RenderDisplay(templateParams));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\DisplayTemplates\DisplaySection.cshtml"
                                  
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
