#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Enum.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Enum_cshtml_ : System.Web.Mvc.WebViewPage<Enum>
    {
        public _Views_Shared_DisplayTemplates_Enum_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\DisplayTemplates\Enum.cshtml"
 if (System.Web.Mvc.Html.EnumHelper.IsValidForEnumHelper(ViewData.ModelMetadata))
{
    // Display Enum using same names (from [Display] attributes) as in editors
    string displayName = null;
    foreach (var item in System.Web.Mvc.Html.EnumHelper.GetSelectList(ViewData.ModelMetadata, Model))
    {
        if (item.Selected)
        {
            displayName = item.Text ?? item.Value;
        }
    }

    // Handle the unexpected case that nothing is selected
    if (string.IsNullOrEmpty(displayName))
    {
        if (Model == null)
        {
            displayName = string.Empty;
        }
        else
        {
            displayName = Model.ToString();
        }
    }

    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Enum.cshtml"
Write(Html.DisplayTextFor(model => displayName));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\DisplayTemplates\Enum.cshtml"
                                              
}
else
{
    // This Enum type is not supported.  Fall back to the text.
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Shared\DisplayTemplates\Enum.cshtml"
Write(Html.DisplayTextFor(model => model));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Shared\DisplayTemplates\Enum.cshtml"
                                        
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
