#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/Link.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_Link_cshtml_ : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_DisplayTemplates_Link_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\DisplayTemplates\Link.cshtml"
  
    var action = ViewData["ActionName"];
    var dataBind = $"text: data.{ViewData.ModelMetadata.PropertyName}, {ViewData["DataBind"]}";
    var cls = ViewData["Class"];
    var href = ViewData["Href"];

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<a");

WriteAttribute("class", Tuple.Create(" class=\"", 218), Tuple.Create("\"", 232)
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Link.cshtml"
, Tuple.Create(Tuple.Create("", 226), Tuple.Create<System.Object, System.Int32>(cls
            
            #line default
            #line hidden
, 226), false)
);

WriteLiteral(" data-bind=\"");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Link.cshtml"
                         Write(dataBind);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-action=\"");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Link.cshtml"
                                                   Write(action);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("href", Tuple.Create(" href=\"", 281), Tuple.Create("\"", 295)
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\Link.cshtml"
, Tuple.Create(Tuple.Create("", 288), Tuple.Create<System.Object, System.Int32>(href
            
            #line default
            #line hidden
, 288), false)
);

WriteLiteral(">\r\n</a>");

        }
    }
}
#pragma warning restore 1591
