#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
    using MvcSiteMapProvider.Web.Html.Models;
    
    #line default
    #line hidden
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/SiteMapNodeModelList.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_SiteMapNodeModelList_cshtml_ : System.Web.Mvc.WebViewPage<MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModelList>
    {
        public _Views_Shared_DisplayTemplates_SiteMapNodeModelList_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n<ul>\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
     foreach (var node in Model) { 

            
            #line default
            #line hidden
WriteLiteral("        <li>");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
       Write(Html.DisplayFor(m => node));

            
            #line default
            #line hidden
WriteLiteral(" \n");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
            
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
             if (node.Children.Any()) {
                
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
           Write(Html.DisplayFor(m => node.Children));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
                                                    
            }

            
            #line default
            #line hidden
WriteLiteral("        </li>\n");

            
            #line 12 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
