#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
    using MvcSiteMapProvider.Web.Html.Models;
    
    #line default
    #line hidden
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/SiteMapNodeModel.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_SiteMapNodeModel_cshtml_ : System.Web.Mvc.WebViewPage<MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModel>
    {
        public _Views_Shared_DisplayTemplates_SiteMapNodeModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
 if (Model.IsCurrentNode && Model.SourceMetadata["HtmlHelper"].ToString() != "MvcSiteMapProvider.Web.Html.MenuHelper")  { 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
} else if (Model.IsClickable) { 
    if (string.IsNullOrEmpty(Model.Description))
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 380), Tuple.Create("\"", 397)
            
            #line 10 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 387), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 387), false)
);

WriteLiteral(">");

            
            #line 10 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
                        Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 447), Tuple.Create("\"", 464)
            
            #line 14 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 454), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 454), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 465), Tuple.Create("\"", 491)
            
            #line 14 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 473), Tuple.Create<System.Object, System.Int32>(Model.Description
            
            #line default
            #line hidden
, 473), false)
);

WriteLiteral(">");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
                                                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");

            
            #line 15 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
    }
} else { 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 17 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 18 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
