


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace StandardWeb.Controllers
{
	using System.Data.Entity;
	using System.Web.Mvc;
	using Orzoo.AspNet.Mvc;
	using StandardWeb.Models.DTO;
	using StandardWeb.Models.PO;
	using StandardWeb.Services;

    public partial class PeopleController : CrudController<Person, int, PersonDto, PersonItemDto, PersonService>
    {
        public PeopleController(DbContext context) : base(context)
        {

        }
    }
}
