


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace StandardWeb.Services
{
	using System.Data.Entity;
	using Orzoo.AspNet.Infrastructure;
	using StandardWeb.Models.PO;

    public partial class PersonService : BaseService<Person, int>
    {
        public PersonService(DbContext context) : base(context)
        {

        }
    }
}
