#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\EditTemplate.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    using Orzoo.AspNet.Extensions;
    using Orzoo.AspNet.Html;
    using Orzoo.AspNet.Mvc;
    using Orzoo.Core.Extensions;
    using Orzoo.Core.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditTemplate.cshtml")]
    public partial class _Views_Shared_EditTemplate_cshtml : System.Web.Mvc.WebViewPage<object>
    {
        public _Views_Shared_EditTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\EditTemplate.cshtml"
  
    Layout = "~/Views/Shared/Layouts/_FormDialogLayout.cshtml";

    var title = Model.GetType().GetAttribute<DisplayNameAttribute>()?.DisplayName ?? string.Empty;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Footer", () => {

WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Shared\EditTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Shared\EditTemplate.cshtml"
      
        var editRole = ViewData["EditRole"]?.ToString();
        var isDetail = Request.Params["state"] == "detail";
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Shared\EditTemplate.cshtml"
Write(isDetail ? Btn.ButtonForEdit(role: editRole) : Btn.ButtonForSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<form");

WriteLiteral(" class=\"p15 form-horizontal\"");

WriteLiteral(" data-title=\"");

            
            #line 19 "..\..\Views\Shared\EditTemplate.cshtml"
                                         Write(title);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\EditTemplate.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 21 "..\..\Views\Shared\EditTemplate.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\EditTemplate.cshtml"
     foreach (var property in Model.GetType().GetProperties())
    {
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\EditTemplate.cshtml"
   Write(Html.EditorSectionGridLayout(property.Name));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\EditTemplate.cshtml"
                                                    
    }

            
            #line default
            #line hidden
WriteLiteral("</form>\r\n");

        }
    }
}
#pragma warning restore 1591
